# -*- coding: utf-8 -*-
"""soil Predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TRda8sCjbvn9kpnZgwRotLvUeXMYbo3R
"""







import torchvision
import torch
from torch.utils.data import DataLoader, Dataset
import torchvision.transforms as T
import numpy as np
from sklearn.preprocessing import LabelEncoder
import torch.nn as nn
from torchvision.models import vgg16
from sklearn.model_selection import train_test_split
import torch.nn.functional as Fun
import cv2

device = 'cuda' if torch.cuda.is_available() else 'cpu'

transforms = T.Compose(
        [T.ToTensor(),
        T.Normalize(mean=[0.485,
           0.456, 0.406],std=[0.229, 0.224, 0.225])]
        )

    
def read_transform(img):
        f = img
        im = cv2.imread(f)
        im = cv2.resize(im, (224,224))
        im = transforms(im)
        return torch.tensor(im,dtype=torch.float).to(device)

def get_model(no_classes):
    model = torchvision.models.vgg16(pretrained=True)
    for param in model.features.parameters():
                   param.requires_grad = False
    model.avgpool = model.avgpool = nn.AdaptiveAvgPool2d(output_size=(1,1))
    model.classifier = nn.Sequential(nn.Flatten(),
                                   nn.Linear(512, 128),
                                   nn.ReLU(),
                                   nn.Dropout(0.2),
                                   nn.Linear(128, no_classes),
                                   nn.Sigmoid())

    return model.to(device)

def load_model(model_path, classes):
  model = get_model(classes)
  state_dict = torch.load(model_path)
  return model,state_dict

soil_classes = {'Black_soil': 0,
            'Clay_soil': 1,
            'Loamy_soil': 2,
            'Red_soil': 3,
            'Sandy_soil': 4}
soils = {
    "Clay_soil": {
        "composition": "high in clay particles, low in sand and organic matter, making the soil dense and heavy. It has the ability to retain moisture well but can easily become waterlogged and compacted if not managed properly. ",
        "description": "Clay soil is typically found in cooler, wetter regions and is known for its ability to hold nutrients well, but can be difficult to work with due to its density and tendency to become compacted. It is best suited for crops that prefer moist soil and can handle heavy soil, such as root vegetables."
    },
    "Red_soil": {
        "composition": "high in iron and aluminum, low in organic matter and nutrients. This soil is known for its poor drainage and is commonly found in tropical and subtropical regions.",
        "description": "Red soil is typically found in regions with high temperatures and rainfall. It is generally less fertile than other soil types and can be challenging to grow crops in. However, with proper management, it can be used to grow crops such as rice, cotton, and sugarcane."
    },
    "Sandy_soil": {
        "composition": "high in sand particles, low in clay and organic matter. This soil has good drainage and is dry and warm.",
        "description": "Sandy soil is typically found in warmer regions, and is known for its good drainage and aeration. However, it can be difficult to retain moisture and nutrients in this type of soil. Crops that are well-suited for sandy soil include strawberries, tomatoes, and peppers."
    },
    "Loamy_soil": {
        "composition": "balanced mix of sand, clay, and organic matter. This soil has good drainage and moisture retention, making it fertile and easy to work with.",
        "description": "Loamy soil is considered the most ideal soil type for growing a wide variety of crops. It is a well-balanced soil, with the right amount of sand, clay, and organic matter, making it easy to work with and providing good drainage and moisture retention. Crops that thrive in loamy soil include vegetables, fruits, and flowers."
    },
    "Black_soil": {
        "composition": "high in organic matter and clay, rich in nutrients. This soil has good water-holding capacity, which makes it suitable for agriculture.",
        "description": "Black soil is also known as 'black cotton soil' because it is ideal for growing cotton. It is typically found in regions with high temperatures and low rainfall. The soil is rich in nutrients and has good water-holding capacity, making it well-suited for growing a wide variety of crops, including wheat, sugarcane, and soybeans."
    }
}

fclass = list(soil_classes.keys())



def predict(image):
  img = read_transform(image)
  img = img.to(device)
  model, state_dict = load_model('models/soil/soil.pth', 5)
  model.load_state_dict(state_dict)
  output = model(img.unsqueeze_(0))
  pred, conf = output.max(-1)
  
  return fclass[conf.item()]#, pred soils[fclass[conf.item()]],

# print(predict('image/temp_soil.jpeg'))

